project:
  type: website

website:
  title: "Robert Granger"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: apps.qmd
        text: Apps

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

