project:
  type: website
  output-dir: docs

website:
  title: "Robert Granger"
  navbar:
    collapse: false
    background: "#990000"
    left:
      - href: index.qmd
        text: Home
      - href: about/about.qmd
        text: About
      - href: research/research.qmd
        text: Research
      - href: teaching/teaching.qmd
        text: Teaching
      - href: apps/apps.qmd
        text: Apps
  page-footer:
    background: "#990000"
    border: true
    right: "© 2022, Robert E. Granger"
    center:
      <a href="mailto:rgranger@iu.edu"><i class="bi bi-envelope"></i></a>
      <a href="https://www.linkedin.com/in/rgranger617"><i class="bi bi-linkedin"></i></a>
      <a href="https://twitter.com/rgranger617"><i class="bi bi-twitter"></i></a>
      <a href="https://github.com/rgranger617"><i class="bi bi-github"></i></a>
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    backgroundcolor: "#EEEDEB"

editor: visual



execute: 
  freeze: false