# Automatically build the list of Purdue media used by the Monty Hall game.
# This runs before `quarto render` via _quarto.yml.

media_dir <- file.path("apps", "apps", "montyhall", "images")
out_file  <- file.path("apps", "apps", "montyhall", "purdue-media.js")

if (!dir.exists(media_dir)) {
  stop("Monty Hall images folder not found: ", media_dir)
}

files <- list.files(media_dir, full.names = FALSE, ignore.case = TRUE)
files <- files[grepl("^purdue", files, ignore.case = TRUE)]
files <- files[grepl("\\.(mp4|webm|mov|m4v|jpg|jpeg|png|gif|webp)$", files, ignore.case = TRUE)]
files <- sort(files)

if (length(files) == 0) {
  warning("No Purdue media found. Add files beginning with 'purdue' to ", media_dir)
}

# JSON encoding without requiring an extra R package.
escape_js <- function(x) {
  x <- gsub("\\\\", "\\\\\\", x)
  x <- gsub('"', '\\"', x, fixed = TRUE)
  paste0('"images/', x, '"')
}

js <- paste0(
  "// AUTO-GENERATED by build-purdue-media.R. Do not edit by hand.\n",
  "window.PURDUE_MEDIA = [", paste(vapply(files, escape_js, character(1)), collapse = ", "), "];\n"
)
writeLines(js, out_file, useBytes = TRUE)
message("Monty Hall: found ", length(files), " Purdue media file(s).")
