// AUTO-GENERATED by build-purdue-media.R. Do not edit by hand.
window.PURDUE_MEDIA = ["images/purduealpaca.mp4", "images/purduebull.mp4", "images/purduecat.mp4", "images/purduechicken.mp4", "images/purduechicken2.mp4", "images/purduecow.mp4", "images/purduedog1.mp4", "images/purduedog2.mp4", "images/purduedonkey.mp4", "images/purdueduck.mp4", "images/purduegoat.mp4", "images/purduegoose.mp4", "images/purduehorse.mp4", "images/purduellama.mp4", "images/purdueowl.mp4", "images/purduepig.mp4", "images/purduerabbit.mp4", "images/purduesheep.mp4", "images/purdueturkey.mp4"];

