---
title: "Information"
---

## **Letters of Recommendation**

I have been frequently asked to write letters of recommendation for a variety of situations including academic programs, teaching reviews, scholarships, etc... Most of the time, I'm willing to write these letters, but I've found it more and more difficult, especially for individuals that I have infrequent interactions. Hence, I'm putting forward some guidelines that you'll need to agree before I will write a letter.

**Guidelines for who I will write a letter:**

1\) Do I know you? Could I pick you out of a crowd and say your name?

2\) If I don't know your name, did you take a class with me?

If you fit under category 1), then yes, I will write you a letter. If you fit under category 2), then it's a likely yes, but we may need to have a longer conversation. If you do not fit under 1) or 2), you're welcome to ask, but I will almost certainly reject writing you a letter.

**What I need to write a letter:**

If you ask me for a letter of recommendation before reviewing this section, then I will likely point you to this page. As such, just follow up with an additional email that includes all of the following. Note that I will not write you a letter unless you include all 7 of these parts.

1\) What are you applying for? Be specific. I need to know if it's an academic program, scholarship, study abroad, etc... Could it be multiple programs? Feel free to include some links.

2\) Why should I write the letter on your behalf? Why did you not seek someone else out (this is especially important if I don't know who you are)? Please be honest and forthright. I understand obtaining letters can be difficult, especially for undergraduates.

3\) Please provide some sort of personal statement or essay.

4\) Please provide a resume/CV and/or transcripts. The more you can tell me, the better the letter I can write.

5\) Answer these two questions:

-   For what class(es) was I your instructor and how did you distinguish yourself in my class(es)?

-   What are your long term goals? How will this program/scholarship help you achieve these goals?

6\) Please provide any deadlines for your letter of recommendation.

7\) Please explicitly state in your email that you give me written permission to share any information that is part of your educational record such as your GPA, class grades, and/or relative standing in the class in your recommendation letter. [Technically, sharing these things in your letter would be a violation of FERPA without your written permission.](https://registrar.indiana.edu/policies/ferpa/student-privacy-staff.html)

**Things I will not write letters of recommendation for:**

At this time, I will not write letters of recommendation for PhD programs. Standard things I have written letters of recommendation for in the past include teaching reviews, Master's level programs, school transfers, study abroad, and various scholarships.
